### ISSUE TITLE
Usability: open interface when launching .exe file

### ISSUE THREAD

**Issue by raveren** [ryanSN/winmoji#102]
It would make adding a windows-wide keyboard shortcut possible. Currently if the app is in the tray, launching the exe does nothing.

**Comment by ryanSN** [comment]
This sounds like a bug.
With it installed there currently is a global shortcut that is registered. `windows key + shift + E` will open the application if minimized.

Clicking the exe will also do a check if trying to open a second application, which _should_ be opening the application from a minimized state.
