### ISSUE TITLE
Wrong font used for "Recent" emoji title

### ISSUE THREAD

**Issue by Darthagnon** [ryanSN/winmoji#162]
**Describe the bug**
The font used for the "Recent" title in the emoji list looks like Times New Roman. Would it be possible to change the font to Segoe UI (Windows system default)?

**Comment by ryanSN** [comment]
🤔  I'll take a look. I don't specifically set the font.

**Comment by ryanSN** [comment]
nevermind I do! https://github.com/ryanSN/winmoji/blob/2f254bed116e8e5225c8913546ef4e874695b18c/app/static/about.html#L9

**Comment by Darthagnon** [comment]
My apologies for raising this issue; I was testing winmoji, and on my PC it was showing up as some serif font that looked like Times New Roman, almost as if it was some fallback font being loaded or something. 

Thank you so much for making winmoji; I've been looking everywhere for a good emoji picker for pre-Win10 Windows, and winmoji is the best I've found!

**Comment by ryanSN** [comment]
No, thanks so much for finding it.
