### ISSUE TITLE
Request to add a github action

### ISSUE THREAD

**Issue by Jassi10000** [ryanSN/winmoji#211]
I see that the repo is quite engaging
I would love to see a github - action welcoming all the new contributors on their issues and Prs

If you love the idea , assign me

**Comment by ryanSN** [comment]
I see you spam the same message across repos. I also probably wouldn't do this with a github actions and use a bot instead to properly enforce coding practices/ guidelines and sign off of contributions. 

I'm good.

**Comment by Jassi10000** [comment]
> I see you spam the same message across repos. I also probably wouldn't do this with a github actions and use a bot instead to properly enforce coding practices/ guidelines and sign off of contributions.
> 
> I'm good.


I wanna say two things , 

1. This is not spamming , am just contributing some valuable stuff to repositories 
2. If you don't want it , its ok

**Comment by ryanSN** [comment]
https://github.com/validatorjs/validator.js/issues/1832
https://github.com/ryanSN/winmoji/issues/211
https://github.com/falconry/falcon/issues/1984

its the same message over and over with the exact same code, which is the starter code for https://github.com/actions/first-interaction. You also mentioning engaging without looking at any of the PRs for an action that only messages for someone new on a PR.

If you had looked at this repo, you would have seen that 95%+ of the PR's beside dependency updates are my PRs so the value add here is very little to none in this case.
