### ISSUE TITLE
Implement alternative emoji vendors

### ISSUE THREAD

**Issue by Twilightssuperb** [ryanSN/winmoji#244]
Original Win 8.1 doesn't support newer emojis. To see them and choose some symbols for copying, I need to update OS to Win 10 or 11.

But if you implement Twemoji font (open source by Twitter; best solution) or Openmoji, I'd be able to see full emoji table at WinMoji without empty squares.

Also I use Emoji keyboard Chrome extension by JoyPixels (former EmojiOne vendor), it's marvelous.

**Comment by ryanSN** [comment]
At this time this won't be supported. winMoji is simply grabbing the supported emojis that windows is supporting at that time per the https://home.unicode.org/ specs and using its built in front to display it. winMoji doesn't install any fonts as that carries a larger file size. winMoji was created to simply expose the already supported emojis in windows 10 before windows 10 supported a ui for this case.

It just so happened to provide a ui for windows 7 , and 8 users that install the sego ui font (granted uncolored emojis).

Allowing the ability to user other fonts though possible, means it up the user to make sure who they are sending the unicode to also supports that emoji. 
As this is directed at windows, if you install a new font that supports a emoji that is not in version 12, the other windows user will simply see a X'd square unless they install the same font you have.

**Comment by Twilightssuperb** [comment]
> Allowing the ability to use other fonts though possible, means it up the user to make sure who they are sending the unicode to also supports that emoji.

It's still would be welcome, but it's your prerogative (to not implement this), no doubt.
