### ISSUE TITLE
Windows 7 initial state

### ISSUE THREAD

**Issue by sergeevabc** [ryanSN/winmoji#275]
![2023-1224-1113 winmoji](https://github.com/ryanSN/winmoji/assets/373718/b603532a-3c95-4dfb-b420-de9e50bc4851)

After launching Winmoji 2.3.0 under Windows 7 x64, should it look like this, or do you recommend performing some additional actions with fonts to improve the display of emojis?

**Comment by Twilightssuperb** [comment]
Yep, I suggested some solution at #244, but it's still open for more than year...

So you can look for one more emoji picker:
- https://alternativeto.net/software/feeling-finder/about/ (portable version is available)
- https://alternativeto.net/software/ef-ck-chat-keyboard/about/

**Comment by sergeevabc** [comment]
@Twilightssuperb, I managed to slightly mitigate the issue by modifying Segoe UI Symbol font via [automated script](https://github.com/13rac1/twemoji-color-font/?tab=readme-ov-file#replace-the-default-windows-emoji-fonts) that added more emojis from Twemoji, however they're still black and white. Not much, but at least something. This is how it looks now in Feeling Finder app which you recommended earlier.

![2023-1231-0338 feeling finder windows7](https://github.com/ryanSN/winmoji/assets/373718/c0f22f43-d667-4a0c-9fae-f363b04c4c6d)

**Comment by ryanSN** [comment]
@Twilightssuperb @sergeevabc 
Its all font based, winmoji doesn't install any fonts, but uses the emoji spec that windows uses. Which is most of the time many versions behind.  See https://github.com/ryanSN/winmojilib, windows 10 supports Emoji Spec Version 12.

Here is the recent proposals https://home.unicode.org/emoji/about-emoji/
If you install a font that supports Ice cube, and send that to someone they most likely will not see it unless they install a font that does or windows/mac/android/ios updates their font to support it. Thats the issue with other emoji pickers and the risk you take, winMoji wasn't built for that, it was built to expose the fonts windows had but didn't have a UI for.

winMoji was built for windows 10_before_ windows had supported the emoji keyboard but had the font support. It was made to mimic what MacOS had at thee time and to push windows to support such a keyboard. 

The older windows support is "it works" but you'll need to go download the emoji fonts you want, which would be the `Segoe UI Emoji` font and winmoji will give you a UI that windows 7, and 8 lack. But windows 10+ has.

**Comment by ryanSN** [comment]
> @Twilightssuperb, I managed to slightly mitigate the issue by modifying Segoe UI Symbol font via [automated script](https://github.com/13rac1/twemoji-color-font/?tab=readme-ov-file#replace-the-default-windows-emoji-fonts) that added more emojis from Twemoji, however they're still black and white. Not much, but at least something. This is how it looks now in [Feeling Finder](https://github.com/Merrit/feeling_finder) app which you recommended earlier.
> 
> ![2023-1231-0338 feeling finder windows7](https://private-user-images.githubusercontent.com/373718/293485552-c0f22f43-d667-4a0c-9fae-f363b04c4c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDA3NDUsIm5iZiI6MTcwNDQwMDQ0NSwicGF0aCI6Ii8zNzM3MTgvMjkzNDg1NTUyLWMwZjIyZjQzLWQ2NjctNGEwYy05ZmFlLWYzNjNiMDRjNGM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQyMDM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTJhZjdkMDNiOTU3YzNlNmZmOWFmM2Q1YTMwZGY3YTRkNjk4OTgxODlhNmVmNmUwNDdiYzhjNmI2ZDJlOGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IUqnUMc9BWewFtJw2YFw2Ew_HouzwHILzUROf5ZKM4)

I haven't run this on windows 7 in awhile, but from previous users experience windows 7 and 8 will show the emojis as outlines and not colors with the sego ui emoji font. Thats a windows issue.
