### ISSUE TITLE
Add a small "History" section

### ISSUE THREAD

**Issue by TheGrimSilence** [ryanSN/winmoji#84]
Users should be able to quickly open winmoji and select a previously used emoji without having to search. 

Placement: Separate tab, a small row below the search bar, side panel.

This would make the application a quicker and easier tool for the average user just trying to open then close winmoji.

**Comment by TheGrimSilence** [comment]
"Last used" or Last Used" would actually be more preferable.

**Comment by ryanSN** [comment]
Thanks for the feedback, where you thinking something like the last 5 emojis used?

**Comment by TheGrimSilence** [comment]
Kind of, yes. Either 5 or 10. However many you feel necessary. I guess you could create an array, and when an emoji is used just add that to the top of the stack. Once the array is full remove or pop the last one and add the next.

**Comment by ryanSN** [comment]
This will be included in the next release, code already exists on master.
