### ISSUE TITLE
Winmoji can exist as more than one instance

### ISSUE THREAD

**Issue by TheGrimSilence** [ryanSN/winmoji#85]
So something I notice occasionally is that either in the tray or in the Task Manager, there are often times more than one instance of Winmoji. I think if a user clicks on the executable, Winmoji should do a check to see if there's already an open instance. That way Winmoji doesn't accidentally take up more usage. If there's an open instance then either open it or reconnect it.

Here you can see by clicking on a shortcut Winmoji practically doubled by creating a new instance instead of checking for an active one.
![screenshot_25](https://user-images.githubusercontent.com/11479772/47393849-b1e5fb80-d6ee-11e8-953d-4a7b32ed78fd.png)
![screenshot_26](https://user-images.githubusercontent.com/11479772/47393850-b1e5fb80-d6ee-11e8-818a-bd71df229a12.png)

**Comment by ryanSN** [comment]
@TheGrimSilence nice find 👍 
Just needs to check the [apprequestsingleinstancelock()](https://electronjs.org/docs/api/app#apprequestsingleinstancelock)
